### ISSUE TITLE
使用Hexo+GitHub搭建博客 | dazhi blog

### ISSUE THREAD

**Issue by wz-dazhi** [wz-dazhi/gitment-comments#1]
http://dazhige.top/2018/05/22/%E4%BD%BF%E7%94%A8Hexo-GitHub%E6%90%AD%E5%BB%BA%E5%8D%9A%E5%AE%A2.html#more

**Comment by wz-dazhi** [comment]
第一次编写博客,抄袭的别人...

**Comment by huichao0102** [comment]
厉害了 ，很棒的一张帖子，给人一种春天要来了吗？的感觉
